### ISSUE TITLE
Nothing appears even after updating the client ID and secret

### ISSUE THREAD

**Issue by rjchen2013** [IntuitDeveloper/SampleOAuth2_UsingPythonClient#1]
After doing what is said in the readme, I entered localhost:8000/app only to see an empty page. This is what I am seeing right now.

![capture](https://user-images.githubusercontent.com/5550734/49427933-a0a90800-f7df-11e8-8d01-f8a2c9cbe2fc.PNG)

Can I know what should I be seeing instead? 

Additionally, I have added http://localhost:8000/app/callback to the Redirect URIs in the Intuit Developer's Key section so I assume I do not have to change the one in the settings.py right?

**Comment by nbhambhani** [comment]
Hi @rjchen2013 seems like styling applied for index page creates issues in some cases. Can you pull latest changes or comment out this line: https://github.com/IntuitDeveloper/SampleOAuth2_UsingPythonClient/blob/master/app/templates/index.html#L5
Let me know if this works for you.
