### ISSUE TITLE
Need to run migrate before starting

### ISSUE THREAD

**Issue by cjcole8** [IntuitDeveloper/SampleOAuth2_UsingPythonClient#3]
If you start using this app before running "python manage.py migrate", you get an error because it tries to store the auth_code in the session, but the sessions table hasn't been setup yet.

The easiest way to fix this is probably just include the sqlite database in the git package, like here: https://github.com/IntuitDeveloper/OAuth2PythonSampleApp

**Comment by nbhambhani** [comment]
@cjcole8 thanks for reporting this, I've committed the changes. Let me know if you find some issues.
